# Generated by Django 6.0 on 2025-12-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emailVerified', models.BooleanField(db_column='emailVerified', default=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_id', models.CharField(db_column='accountId', max_length=255)),
                ('provider_id', models.CharField(db_column='providerId', max_length=255)),
                ('user_id', models.CharField(db_column='userId', max_length=255)),
                ('access_token', models.TextField(db_column='accessToken', null=True)),
                ('refresh_token', models.TextField(db_column='refreshToken', null=True)),
                ('id_token', models.TextField(db_column='idToken', null=True)),
                ('access_token_expires_at', models.DateTimeField(db_column='accessTokenExpiresAt', null=True)),
                ('refresh_token_expires_at', models.DateTimeField(db_column='refreshTokenExpiresAt', null=True)),
                ('scope', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
