# Generated by Django 6.0.1 on 2026-01-18 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('media_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('anime', 'Anime'), ('movie', 'Movie')], max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
